spring:
  sql:
    init:
      mode: always
  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:mysql://localhost/questionize-db?createDatabaseIfNotExist=true&useSSL=false&serverTimezone=America/Sao_Paulo}
    username: ${SPRING_DATASOURCE_USERNAME:root}
    password: ${SPRING_DATASOURCE_PASSWORD:}
  jpa:
    defer-datasource-initialization: true
    database: mysql
    database-platform: org.hibernate.dialect.MySQLDialect
    show-sql: false
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
  jackson:
    serialization:
      write_dates_as_timestamps: false
jwt:
  secret: ${JWT_SECRET:mysecretkey}
  expiration-time-in-hours: 10
  expiration-time-in-days: 7