spring:
  datasource:
    url: jdbc:mysql://localhost/questionize-db?createDatabaseIfNotExist=true&useSSL=false&serverTimezone=America/Sao_Paulo
    username: root
    password:
  jpa:
    database: mysql
    database-platform: org.hibernate.dialect.MySQLDialect
    show-sql: false
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
  jackson:
    serialization:
      write_dates_as_timestamps: false
